import Link from "next/link";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";
const copy = {
  sr: { eyebrow: "Cookies", title: "Kolačići i analitika moraju imati jasnu svrhu.", text: "DaniniNet može koristiti tehničke kolačiće, osnovnu analitiku i budući tracking samo kada pomažu funkcionalnosti, merenju signala ili poboljšanju sadržaja.", blocks: [["Tehnička funkcionalnost", "Neki kolačići mogu biti potrebni da sajt radi stabilno, da pamti jezik ili da podrži osnovne funkcije."], ["Analitika", "Analitika se koristi da se razume šta ljudi čitaju, gde klikću i koji sadržaj ima tržišni signal."], ["Marketing", "Marketing tracking ne sme biti skriven. Ako se koristi za kampanje, retargeting ili affiliate merenje, treba biti jasno označen."], ["Princip", "Ne prikupljati više nego što je potrebno. Ne koristiti tracking kao zamenu za poverenje." ]]},
  de: { eyebrow: "Cookies", title: "Cookies und Analyse brauchen einen klaren Zweck.", text: "DaniniNet kann technische Cookies, Basisanalyse und künftiges Tracking nutzen, wenn sie Funktion, Signalmessung oder Inhaltsverbesserung unterstützen.", blocks: [["Technische Funktion", "Einige Cookies können nötig sein, damit die Website stabil funktioniert, Sprache merkt oder Grundfunktionen unterstützt."], ["Analyse", "Analyse hilft zu verstehen, was gelesen wird, wo geklickt wird und welche Inhalte Marktsignale erzeugen."], ["Marketing", "Marketing-Tracking darf nicht versteckt werden. Kampagnen, Retargeting oder Affiliate-Messung müssen klar erklärt werden."], ["Prinzip", "Nicht mehr erfassen als nötig. Tracking ersetzt kein Vertrauen." ]]},
  en: { eyebrow: "Cookies", title: "Cookies and analytics need a clear purpose.", text: "DaniniNet may use technical cookies, basic analytics and future tracking only when they support functionality, signal measurement or content improvement.", blocks: [["Technical function", "Some cookies may be needed for site stability, language preference or basic functionality."], ["Analytics", "Analytics helps understand what people read, where they click and which content creates a market signal."], ["Marketing", "Marketing tracking must not be hidden. Campaigns, retargeting or affiliate measurement should be explained clearly."], ["Principle", "Do not collect more than needed. Tracking is not a replacement for trust." ]]},
} as const;
export default async function CookiesPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; const lang: Locale = normalizeLocale(locale); const t = copy[lang]; return <SiteShell locale={lang} currentPath={`/${lang}/legal/cookies`}><SectionIntro eyebrow={t.eyebrow} title={t.title} text={t.text}/><section className="mx-auto grid max-w-7xl gap-6 px-6 pb-16 md:grid-cols-2">{t.blocks.map(([title,text]) => <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-4 leading-8 text-[#706a5d]">{text}</p></article>)}</section><section className="bg-[#07142b] text-white"><div className="mx-auto max-w-7xl px-6 py-14"><Link href={`/${lang}/legal`} className="inline-flex rounded-full bg-[#d9ecff] px-6 py-3 text-sm font-semibold text-[#07142b]">Legal & Trust</Link></div></section></SiteShell>; }
