import Link from "next/link";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";

const copy = {
  sr: { eyebrow: "Cookies", title: "Kolačići i analitika moraju imati jasnu svrhu.", text: "DaniniNet može koristiti tehničke kolačiće, osnovnu analitiku i budući tracking samo kada pomažu funkcionalnosti, merenju signala ili poboljšanju sadržaja. Tracking ne sme biti skriven i ne sme zameniti poverenje.", notice: "Konačna Cookie Policy verzija mora se uskladiti sa stvarno aktivnim alatima na sajtu: hosting, analitika, email forme, checkout, video embed i affiliate merenje.", blocks: [["Neophodni kolačići", "Ovi kolačići mogu biti potrebni za stabilan rad sajta, sigurnost, jezičke postavke, osnovnu navigaciju i tehničke funkcije koje korisnik očekuje."], ["Analitički kolačići", "Analitika pomaže da se razume koje stranice korisnici čitaju, gde klikću, koliko se zadržavaju i koji sadržaj ima tržišni signal. U EU kontekstu, analitika treba da bude povezana sa jasnom informacijom i odgovarajućim pristankom kada je potreban."], ["Marketing i affiliate merenje", "Ako se koriste kampanje, retargeting, affiliate parametri ili merenje konverzija, to mora biti jasno opisano. Korisnik treba da zna da klik može biti meren u svrhu isporuke, analitike ili provizije."], ["Video i eksterni embed", "Ako se na stranicu ubaci video iz Gemini/YouTube/Vimeo ili eksterni player, taj servis može imati sopstvene cookies i pravila privatnosti. Takve integracije treba objašnjavati pre aktivnog praćenja."], ["Pristanak i izbor", "Kada je potreban cookie consent, korisnik treba da može da prihvati, odbije ili promeni podešavanja za kategorije koje nisu neophodne."], ["Minimalni princip", "DaniniNet ne treba da prikuplja više podataka nego što je potrebno za funkcionalnost, bezbednost, merenje osnovnog signala i poboljšanje sadržaja."]], final: "Kolačići su tehnički sloj poverenja: korisnik mora razumeti šta se meri, zašto se meri i kako može da upravlja izborom." },
  de: { eyebrow: "Cookies", title: "Cookies und Analyse brauchen einen klaren Zweck.", text: "DaniniNet kann technische Cookies, Basisanalyse und künftiges Tracking nutzen, wenn sie Funktion, Signalmessung oder Inhaltsverbesserung unterstützen. Tracking darf nicht versteckt werden.", notice: "Die finale Cookie Policy muss mit tatsächlich aktiven Tools abgestimmt werden: Hosting, Analytics, E-Mail-Formulare, Checkout, Video-Embeds und Affiliate-Messung.", blocks: [["Notwendige Cookies", "Diese Cookies können für stabilen Betrieb, Sicherheit, Spracheinstellungen, Navigation und erwartete Grundfunktionen erforderlich sein."], ["Analyse-Cookies", "Analyse hilft zu verstehen, welche Seiten gelesen werden, wo Nutzer klicken, wie lange sie bleiben und welche Inhalte Marktsignale erzeugen. Im EU-Kontext braucht dies klare Information und ggf. Einwilligung."], ["Marketing und Affiliate-Messung", "Kampagnen, Retargeting, Affiliate-Parameter oder Conversion-Messung müssen klar erklärt werden. Nutzer sollten wissen, ob ein Klick gemessen wird."], ["Video und externe Embeds", "Wenn Gemini/YouTube/Vimeo oder externe Player eingebunden werden, können diese eigene Cookies und Datenschutzregeln nutzen."], ["Einwilligung und Auswahl", "Wenn Cookie Consent erforderlich ist, sollten Nutzer nicht notwendige Kategorien akzeptieren, ablehnen oder ändern können."], ["Minimalprinzip", "DaniniNet sollte nicht mehr Daten erfassen als für Funktion, Sicherheit, Basissignal und Inhaltsverbesserung nötig."]], final: "Cookies sind ein technischer Vertrauenslayer: Nutzer müssen verstehen, was gemessen wird, warum es gemessen wird und wie sie ihre Auswahl steuern können." },
  en: { eyebrow: "Cookies", title: "Cookies and analytics need a clear purpose.", text: "DaniniNet may use technical cookies, basic analytics and future tracking only when they support functionality, signal measurement or content improvement. Tracking must not be hidden and must not replace trust.", notice: "The final Cookie Policy must match the tools actually active on the site: hosting, analytics, email forms, checkout, video embeds and affiliate measurement.", blocks: [["Necessary cookies", "These cookies may be required for stable site operation, security, language settings, basic navigation and expected technical functions."], ["Analytics cookies", "Analytics helps understand which pages users read, where they click, how long they stay and which content creates a market signal. In an EU context, analytics should be connected to clear information and appropriate consent where required."], ["Marketing and affiliate measurement", "Campaigns, retargeting, affiliate parameters or conversion measurement must be explained clearly. Users should know when a click may be measured for delivery, analytics or commission purposes."], ["Video and external embeds", "If a Gemini/YouTube/Vimeo video or external player is embedded, that service may use its own cookies and privacy rules. Such integrations should be explained before active tracking."], ["Consent and choice", "Where cookie consent is required, users should be able to accept, reject or change non-essential categories."], ["Minimum principle", "DaniniNet should not collect more data than needed for function, security, basic signal measurement and content improvement."]], final: "Cookies are a technical layer of trust: users must understand what is measured, why it is measured and how they can manage their choice." },
} as const;

export default async function CookiesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const lang: Locale = normalizeLocale(locale);
  const t = copy[lang];
  return <SiteShell locale={lang} currentPath={`/${lang}/legal/cookies`}><SectionIntro eyebrow={t.eyebrow} title={t.title} text={t.text}/><section className="mx-auto max-w-7xl px-6 pb-10"><div className="rounded-[2rem] border border-[#d7b46a]/40 bg-[#fff8e7] p-7 text-[#3b3426] shadow-sm"><p className="text-sm uppercase tracking-[0.22em] text-[#9a6b1f]">Implementation note</p><p className="mt-3 max-w-5xl leading-8">{t.notice}</p></div></section><section className="mx-auto grid max-w-7xl gap-6 px-6 pb-16 md:grid-cols-2">{t.blocks.map(([title,text]) => <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-[#15130f]">{title}</h2><p className="mt-4 leading-8 text-[#706a5d]">{text}</p></article>)}</section><section className="bg-[#07142b] text-white"><div className="mx-auto max-w-7xl px-6 py-14"><p className="max-w-4xl text-xl leading-9 text-slate-300">{t.final}</p><Link href={`/${lang}/legal`} className="mt-8 inline-flex rounded-full bg-[#d9ecff] px-6 py-3 text-sm font-semibold text-[#07142b]">Legal & Trust</Link></div></section></SiteShell>;
}
