import Link from "next/link";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";
const copy = {
  sr: { eyebrow: "Terms", title: "Uslovi korišćenja DaniniNet sajta i digitalnih proizvoda.", text: "Korišćenjem DaniniNet-a korisnik prihvata da su sadržaj, proizvodi i case study materijali informativni i edukativni, uz jasne granice odgovornosti.", blocks: [["Sajt", "Sajt služi za edukaciju, prezentaciju digitalnih proizvoda, blog sadržaj, affiliate preporuke i trust informacije."], ["Digitalni proizvodi", "Kupovina i isporuka mogu ići preko eksternih servisa kao što je Gumroad. Konkretni uslovi zavise od proizvoda i checkout provajdera."], ["Eksterni linkovi", "DaniniNet može voditi ka eksternim sajtovima, servisima ili affiliate partnerima. Korisnik sam proverava njihove uslove."], ["Odgovornost", "DaniniNet ne garantuje prodaju, profit, investitora, izvodljivost, zdravlje ili drugi rezultat." ]]},
  de: { eyebrow: "Terms", title: "Nutzungsbedingungen für DaniniNet und digitale Produkte.", text: "Mit der Nutzung von DaniniNet akzeptieren Nutzer, dass Inhalte, Produkte und Case Studies informativ und edukativ sind, mit klaren Grenzen der Verantwortung.", blocks: [["Website", "Die Website dient Bildung, Präsentation digitaler Produkte, Blog-Inhalten, Affiliate-Empfehlungen und Trust-Informationen."], ["Digitale Produkte", "Kauf und Lieferung können über externe Dienste wie Gumroad erfolgen. Konkrete Bedingungen hängen vom Produkt und Checkout-Anbieter ab."], ["Externe Links", "DaniniNet kann zu externen Websites, Diensten oder Affiliate-Partnern führen. Nutzer prüfen deren Bedingungen selbst."], ["Verantwortung", "DaniniNet garantiert keinen Verkauf, Gewinn, Investor, Machbarkeit, Gesundheit oder sonstiges Ergebnis." ]]},
  en: { eyebrow: "Terms", title: "Terms of use for DaniniNet and digital products.", text: "By using DaniniNet, users accept that content, products and case-study materials are informational and educational, with clear responsibility boundaries.", blocks: [["Website", "The site is used for education, digital product presentation, blog content, affiliate recommendations and trust information."], ["Digital products", "Purchase and delivery may be handled by external services such as Gumroad. Specific terms depend on the product and checkout provider."], ["External links", "DaniniNet may link to external sites, services or affiliate partners. Users review their terms independently."], ["Responsibility", "DaniniNet does not guarantee sales, profit, investors, feasibility, health or any other outcome." ]]},
} as const;
export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; const lang: Locale = normalizeLocale(locale); const t = copy[lang]; return <SiteShell locale={lang} currentPath={`/${lang}/legal/terms`}><SectionIntro eyebrow={t.eyebrow} title={t.title} text={t.text}/><section className="mx-auto grid max-w-7xl gap-6 px-6 pb-16 md:grid-cols-2">{t.blocks.map(([title,text]) => <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-4 leading-8 text-[#706a5d]">{text}</p></article>)}</section><section className="bg-[#07142b] text-white"><div className="mx-auto max-w-7xl px-6 py-14"><Link href={`/${lang}/legal`} className="inline-flex rounded-full bg-[#d9ecff] px-6 py-3 text-sm font-semibold text-[#07142b]">Legal & Trust</Link></div></section></SiteShell>; }
