import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";
type LegalSlug = "impressum" | "privacy" | "cookies" | "terms" | "disclaimer" | "affiliate-disclosure" | "ai-transparentnost" | "health-disclaimer" | "refund-policy";

const allowedSlugs: LegalSlug[] = ["impressum", "privacy", "cookies", "terms", "disclaimer", "affiliate-disclosure", "ai-transparentnost", "health-disclaimer", "refund-policy"];

type LegalPage = { title: string; description: string; eyebrow: string; intro: string; sections: [string, string][]; auditNote?: string };

const copy: Record<Locale, Record<LegalSlug, LegalPage>> = {
  sr: {
    impressum: { title: "Impressum", description: "Kontakt i osnovne informacije o DaniniNet projektu.", eyebrow: "Legal & Trust", intro: "Ova stranica prikazuje osnovni kontakt i identitet projekta DaniniNet kao javnog prodajno-informativnog artifact sloja DaniniHub sistema.", sections: [["Kontakt", "DaniniNet · Kontakt email: info@daninihub.com"], ["Odgovorna urednička logika", "DaniniNet sadržaji se objavljuju kao edukativni, informativni i prodajno-strukturni materijali, uz ljudsku proveru i jasne granice."], ["Napomena", "Informacije na ovoj stranici nisu pravni savet. Konačni poslovni podaci, poreski status i lokalni DACH/Balkan zahtevi moraju biti provereni sa kvalifikovanim stručnjakom."]], auditNote: "Pre plaćenog prometa proveriti pravno tačne podatke vlasnika i obavezne lokalne Impressum elemente." },
    privacy: { title: "Privacy / GDPR", description: "Osnovni principi privatnosti i obrade podataka na DaniniNet sajtu.", eyebrow: "Data protection", intro: "DaniniNet obrađuje minimum podataka potreban za komunikaciju, kupovinu, isporuku digitalnih proizvoda, podršku, newsletter i osnovnu analitiku uz saglasnost.", sections: [["Svrha obrade", "Podaci se mogu koristiti za kontakt, podršku, isporuku proizvoda, newsletter, osnovnu analitiku i odgovore na upite."], ["Eksterni servisi", "Kupovina i isporuka mogu ići preko Gumroad-a, email komunikacija preko Brevo-a ili sličnog servisa, a analitika samo uz odgovarajući consent."], ["Minimalni podaci", "Za support se traže samo email korišćen pri kupovini, naziv proizvoda i opis problema. Ne traže se osetljivi podaci."], ["Prava korisnika", "Korisnik može zatražiti informaciju, ispravku ili brisanje podataka kontaktom na support email."]], auditNote: "Cookie banner i newsletter double opt-in moraju biti usklađeni pre intenzivnog DACH prometa." },
    cookies: { title: "Cookies", description: "Informacije o kolačićima, analitici i tehničkoj funkcionalnosti.", eyebrow: "Cookies", intro: "DaniniNet može koristiti tehničke kolačiće, osnovnu analitiku i buduće marketing alate samo u skladu sa pravilima privatnosti i saglasnosti korisnika.", sections: [["Tehnički kolačići", "Koriste se za osnovnu funkcionalnost sajta i ne bi trebalo da prikupljaju više podataka nego što je potrebno."], ["Analitika", "Ako je uključena, analitika treba da se aktivira uz odgovarajuću saglasnost i minimalno prikupljanje podataka."], ["Marketing alati", "Newsletter, remarketing ili tracking alati ne smeju se koristiti bez jasne informacije i potrebne saglasnosti."], ["Kontrola", "Korisnik može upravljati kolačićima kroz browser i eventualni cookie banner."]] },
    terms: { title: "Terms of Use", description: "Uslovi korišćenja DaniniNet sajta i digitalnih proizvoda.", eyebrow: "Terms", intro: "Korišćenjem DaniniNet sajta korisnik prihvata da je sadržaj edukativnog i informativnog karaktera i da ne zamenjuje stručnu proveru.", sections: [["Digitalni proizvodi", "PDF vodiči, bonus materijali, template-i, kursevi i alati služe za edukaciju i strukturisanje procesa."], ["DaniniHub artifact logika", "Stranice, PDF-ovi, e-knjige, kursevi, template-i, forme i video objave mogu biti nus-proizvodi DaniniHub OS metodologije."], ["Eksterni checkout", "Kupovina može ići preko eksternih servisa kao što je Gumroad, prema njihovim pravilima i uslovima."], ["Odgovornost korisnika", "Korisnik samostalno proverava pravne, finansijske, tehničke, zdravstvene i druge odluke sa kvalifikovanim stručnjacima."]] },
    disclaimer: { title: "Disclaimer", description: "Glavni disclaimer za DaniniNet sadržaj, proizvode i usluge.", eyebrow: "Disclaimer", intro: "DaniniNet objavljuje edukativni i informativni sadržaj iz oblasti digitalnog marketinga, affiliate marketinga, AI alata, zdravog stila života, vode i digitalnih proizvoda.", sections: [["Bez profesionalnog saveta", "Sadržaj ne predstavlja pravni, finansijski, poreski, medicinski, investicioni, urbanistički, tehnički ili profesionalni savet."], ["Bez garancija", "Ne garantujemo zaradu, prodaju, poslovni uspeh, zdravstveni rezultat, investitora, dozvole, izvodljivost ili bilo koji konkretan ishod."], ["AI i ljudska odluka", "AI može pomoći u strukturi i analizi, ali konačna odluka i odgovornost ostaju na čoveku."], ["Stručna provera", "Za važne odluke korisnik treba da konsultuje kvalifikovanog stručnjaka."]] },
    "affiliate-disclosure": { title: "Affiliate Disclosure", description: "Transparentna affiliate napomena za DaniniNet preporuke.", eyebrow: "Affiliate", intro: "Neki linkovi na DaniniNet sajtu mogu biti affiliate linkovi. Ako kupite preko takvih linkova, DaniniNet može ostvariti proviziju bez dodatnog troška za vas.", sections: [["Transparentnost", "Affiliate odnos ne menja obavezu da sadržaj bude informativan, transparentan i odgovoran."], ["Bez garancija", "Ne garantujemo rezultate, zaradu, kvalitet proizvoda ili pogodnost za svakog korisnika."], ["Health/water proizvodi", "Kod proizvoda za vodu, zdrav stil života i uređaje ne daju se medicinske tvrdnje niti garancije zdravstvenog ishoda."], ["Provera", "Pre kupovine korisnik treba samostalno da proveri da li proizvod odgovara njegovim potrebama."]] },
    "ai-transparentnost": { title: "AI transparentnost", description: "Kako DaniniNet koristi AI kroz metodu Pitaj AI — AI pita tebe.", eyebrow: "AI Transparency", intro: "Na DaniniNet-u se AI alati mogu koristiti kao pomoć u strukturiranju ideja, pripremi nacrta, organizaciji sadržaja i analizi, ali ne kao autoritet.", sections: [["AI nije autoritet", "AI ne donosi konačne odluke i ne zamenjuje stručnu proveru."], ["Metoda", "Pitaj AI — AI pita tebe znači da čovek pokreće nameru, AI sme da razjasni do tri podpitanja, a zatim se prelazi na analizu, artifact i proverljiv sledeći korak."], ["Artifact output", "Stranice, PDF vodiči, template-i, kursevi i forme mogu nastati kao artifacti, ali se ne objavljuju bez ljudske kontrole."], ["Odgovornost", "Svaki važan sadržaj treba da prođe ljudsku proveru i uredničku procenu."]] },
    "health-disclaimer": { title: "Health Disclaimer", description: "Granice za sadržaj o zdravlju, vodi i navikama.", eyebrow: "Health", intro: "Sadržaj o zdravlju, vodi, navikama, ishrani i zdravom stilu života ima isključivo informativnu i edukativnu svrhu.", sections: [["Nije medicinski savet", "Sadržaj ne predstavlja medicinski savet, dijagnozu, terapiju ili zamenu za konsultaciju sa lekarom."], ["Bez zdravstvenih garancija", "Ne garantujemo zdravstveni rezultat, poboljšanje stanja ili efekat proizvoda."], ["Affiliate proizvodi", "Preporuke filtera, uređaja, eBook-ova ili health/water proizvoda moraju biti označene i proverene bez medicinskih obećanja."], ["Stručna pomoć", "Za zdravstvena pitanja potrebno je konsultovati kvalifikovanog zdravstvenog stručnjaka."]] },
    "refund-policy": { title: "Refund Policy", description: "Politika povraćaja za DaniniNet digitalne proizvode.", eyebrow: "Refund / Support", intro: "Digitalni proizvodi se isporučuju preko eksternog checkout/delivery sistema. Ova stranica objašnjava osnovnu logiku povraćaja i support-a.", sections: [["Digitalna isporuka", "PDF vodiči, Bonus Pack, template-i i e-knjige mogu biti isporučeni odmah nakon kupovine, pa se refund pravila mogu razlikovati od fizičkih proizvoda."], ["Gumroad pravila", "Ako kupovina ide preko Gumroad-a, primenjuju se i Gumroad uslovi, delivery logika i eventualna refund procedura."], ["Support pre refund-a", "Ako korisnik ne dobije fajlove, prvo treba proveriti checkout email, spam/promotions i Gumroad library, zatim poslati support upit."], ["Bez garancije rezultata", "Nezadovoljstvo tržišnim, poslovnim, zdravstvenim ili investicionim rezultatom nije dokaz neispravnosti proizvoda, jer rezultati nisu garantovani."]] },
  },
  de: {
    impressum: { title: "Impressum", description: "Kontakt und Basisinformationen zu DaniniNet.", eyebrow: "Legal & Trust", intro: "Diese Seite zeigt grundlegende Kontakt- und Projektinformationen für DaniniNet als öffentliche Artifact-Ebene des DaniniHub Systems.", sections: [["Kontakt", "DaniniNet · Kontakt: info@daninihub.com"], ["Redaktionelle Logik", "DaniniNet Inhalte sind edukativ, informativ und strukturell; sie benötigen menschliche Prüfung und klare Grenzen."], ["Hinweis", "Diese Angaben sind keine Rechtsberatung. Finale Geschäfts- und Impressumspflichten müssen lokal geprüft werden."]], auditNote: "Vor bezahltem DACH-Traffic rechtliche Pflichtangaben prüfen." },
    privacy: { title: "Privacy / DSGVO", description: "Datenschutzgrundlagen für DaniniNet.", eyebrow: "Datenschutz", intro: "DaniniNet verarbeitet nur Daten, die für Kommunikation, Kauf, Produktlieferung, Support, Newsletter und Analyse mit Einwilligung nötig sind.", sections: [["Zweck", "Daten können für Kontakt, Support, Produktlieferung, Newsletter und Analyse nach Einwilligung genutzt werden."], ["Externe Dienste", "Kauf und Lieferung können über Gumroad, E-Mail über Brevo oder ähnliche Dienste und Analyse nur mit Consent laufen."], ["Minimale Daten", "Für Support werden Checkout-E-Mail, Produktname und kurze Problembeschreibung benötigt."], ["Nutzerrechte", "Nutzer können Auskunft, Berichtigung oder Löschung per E-Mail anfragen."]], auditNote: "Cookie Banner und Double Opt-in vor intensivem DACH Traffic prüfen." },
    cookies: { title: "Cookies", description: "Informationen zu Cookies und Analyse.", eyebrow: "Cookies", intro: "DaniniNet kann technische Cookies, Analyse und künftige Marketing-Tools nur im Rahmen von Datenschutz und Einwilligung nutzen.", sections: [["Technische Cookies", "Für Basisfunktionen der Website."], ["Analyse", "Nur mit passender Einwilligung und minimaler Datenerhebung."], ["Marketing Tools", "Newsletter, Remarketing oder Tracking nur mit klarer Information und nötiger Einwilligung."], ["Kontrolle", "Nutzer können Cookies im Browser und über Cookie-Banner steuern."]] },
    terms: { title: "Terms of Use", description: "Nutzungsbedingungen für DaniniNet.", eyebrow: "Terms", intro: "Die Nutzung von DaniniNet bedeutet, dass Inhalte als edukativ und informativ verstanden werden und keine Fachprüfung ersetzen.", sections: [["Digitale Produkte", "PDFs, Bonusmaterial, Templates, Kurse und Tools dienen Bildung und Strukturierung."], ["DaniniHub Artifact Logik", "Seiten, PDFs, E-Books, Kurse, Templates, Formulare und Videos können Nebenprodukte der DaniniHub OS Methode sein."], ["Externer Checkout", "Käufe können über Dienste wie Gumroad laufen."], ["Verantwortung", "Nutzer prüfen wichtige Entscheidungen mit qualifizierten Fachleuten."]] },
    disclaimer: { title: "Disclaimer", description: "Haupt-Disclaimer für DaniniNet.", eyebrow: "Disclaimer", intro: "DaniniNet veröffentlicht edukative und informative Inhalte zu digitalem Marketing, Affiliate, KI, Health, Wasser und digitalen Produkten.", sections: [["Keine Beratung", "Keine Rechts-, Finanz-, Steuer-, Medizin-, Investment-, Planungs-, Technik- oder Fachberatung."], ["Keine Garantien", "Keine Garantie für Einkommen, Verkauf, Erfolg, Gesundheit, Investoren, Genehmigungen oder konkrete Ergebnisse."], ["KI und Entscheidung", "KI kann Struktur und Analyse unterstützen, aber die finale Entscheidung bleibt beim Menschen."], ["Fachprüfung", "Wichtige Entscheidungen sollten durch qualifizierte Fachleute geprüft werden."]] },
    "affiliate-disclosure": { title: "Affiliate Disclosure", description: "Affiliate-Hinweis für DaniniNet.", eyebrow: "Affiliate", intro: "Einige Links auf DaniniNet können Affiliate-Links sein. Bei Kauf kann DaniniNet eine Provision erhalten, ohne Mehrkosten für Nutzer.", sections: [["Transparenz", "Affiliate-Beziehungen ändern nicht die Pflicht zu verantwortlichen Inhalten."], ["Keine Garantien", "Keine Garantie für Ergebnisse, Einkommen, Produktqualität oder Eignung."], ["Health/Water Produkte", "Bei Wasser-, Health- und Geräteempfehlungen werden keine medizinischen Behauptungen gemacht."], ["Prüfung", "Nutzer sollten vor Kauf prüfen, ob ein Produkt passt."]] },
    "ai-transparentnost": { title: "KI-Transparenz", description: "Wie DaniniNet KI nutzt.", eyebrow: "AI Transparency", intro: "KI kann bei Struktur, Entwürfen, Organisation und Analyse helfen, ist aber keine Autorität.", sections: [["KI ist keine Autorität", "KI ersetzt keine Entscheidung und keine Fachprüfung."], ["Methode", "Frag die KI — die KI fragt dich bedeutet: Mensch startet, KI darf bis zu drei Rückfragen stellen, danach folgen Analyse, Artifact und nächster Schritt."], ["Artifact Output", "Seiten, PDFs, Templates, Kurse und Formulare können als Artifacts entstehen, aber nicht ohne menschliche Kontrolle."], ["Verantwortung", "Wichtige Inhalte brauchen menschliche Prüfung."]] },
    "health-disclaimer": { title: "Health Disclaimer", description: "Grenzen für Health- und Wasser-Inhalte.", eyebrow: "Health", intro: "Gesundheits-, Wasser-, Ernährungs- und Lifestyle-Inhalte dienen nur Bildung und Information.", sections: [["Keine medizinische Beratung", "Keine Diagnose, Therapie oder Ersatz für ärztliche Beratung."], ["Keine Garantien", "Keine Garantie für gesundheitliche Ergebnisse."], ["Affiliate Produkte", "Filter, Geräte, eBooks oder Health/Water Produkte müssen transparent markiert werden und dürfen keine medizinischen Versprechen enthalten."], ["Fachliche Hilfe", "Bei Gesundheitsfragen qualifizierte Fachleute konsultieren."]] },
    "refund-policy": { title: "Refund Policy", description: "Refund-Logik für DaniniNet digitale Produkte.", eyebrow: "Refund / Support", intro: "Digitale Produkte werden über externe Checkout/Delivery Systeme geliefert. Diese Seite erklärt Refund- und Support-Grundlagen.", sections: [["Digitale Lieferung", "PDFs, Bonus Packs, Templates und E-Books können direkt nach Kauf geliefert werden."], ["Gumroad Regeln", "Bei Gumroad-Käufen gelten auch Gumroad Bedingungen und Delivery-Logik."], ["Support vor Refund", "Bei Delivery-Problemen zuerst Checkout-E-Mail, Spam/Promotions und Gumroad Library prüfen, danach Support kontaktieren."], ["Keine Ergebnisgarantie", "Ausbleibende Geschäfts-, Gesundheits- oder Investment-Ergebnisse sind keine Produktfehler, weil Ergebnisse nicht garantiert werden."]] },
  },
  en: {
    impressum: { title: "Imprint", description: "Contact and basic DaniniNet project information.", eyebrow: "Legal & Trust", intro: "This page provides basic contact and project identity information for DaniniNet as a public artifact layer of the DaniniHub system.", sections: [["Contact", "DaniniNet · Contact: info@daninihub.com"], ["Editorial logic", "DaniniNet content is educational, informational and structural, with human review and clear boundaries."], ["Note", "This information is not legal advice. Final business, tax and local legal requirements must be checked with a qualified professional."]], auditNote: "Before paid traffic, verify legally required business details." },
    privacy: { title: "Privacy / GDPR", description: "Privacy principles for DaniniNet.", eyebrow: "Data protection", intro: "DaniniNet processes the minimum data needed for communication, purchase, product delivery, support, newsletter and basic analytics with consent.", sections: [["Purpose", "Data may be used for contact, support, product delivery, newsletter and basic analytics with consent."], ["External services", "Purchases and delivery may use Gumroad, email may use Brevo or similar services, analytics only with proper consent."], ["Minimal data", "Support should request only checkout email, product name and a short issue description."], ["User rights", "Users may request information, correction or deletion by email."]] },
    cookies: { title: "Cookies", description: "Cookie and analytics information.", eyebrow: "Cookies", intro: "DaniniNet may use technical cookies, analytics and future marketing tools only within privacy and consent rules.", sections: [["Technical cookies", "Used for basic site functionality."], ["Analytics", "Should be used with consent and minimal data collection."], ["Marketing tools", "Newsletter, remarketing or tracking tools require clear information and required consent."], ["Control", "Users can manage cookies in browser and cookie banner settings."]] },
    terms: { title: "Terms of Use", description: "Terms for using DaniniNet.", eyebrow: "Terms", intro: "Using DaniniNet means understanding the content as educational and informational and not a replacement for professional review.", sections: [["Digital products", "PDFs, bonus materials, templates, courses and tools are for education and process structure."], ["DaniniHub artifact logic", "Pages, PDFs, e-books, courses, templates, forms and videos may be by-products of the DaniniHub OS method."], ["External checkout", "Purchases may use external services such as Gumroad."], ["User responsibility", "Users should verify important decisions with qualified professionals."]] },
    disclaimer: { title: "Disclaimer", description: "Main disclaimer for DaniniNet.", eyebrow: "Disclaimer", intro: "DaniniNet publishes educational and informational content about digital marketing, affiliate marketing, AI tools, health, water and digital products.", sections: [["No professional advice", "Content is not legal, financial, tax, medical, investment, planning, technical or professional advice."], ["No guarantees", "We do not guarantee income, sales, business success, health results, investors, permits, feasibility or any specific outcome."], ["AI and human decision", "AI may help with structure and analysis, but final decision and responsibility remain human."], ["Professional review", "Important decisions should be reviewed with qualified professionals."]] },
    "affiliate-disclosure": { title: "Affiliate Disclosure", description: "Affiliate disclosure for DaniniNet recommendations.", eyebrow: "Affiliate", intro: "Some links on DaniniNet may be affiliate links. If you buy through such links, DaniniNet may earn a commission at no additional cost to you.", sections: [["Transparency", "Affiliate relationships do not change the duty to keep content informative and responsible."], ["No guarantees", "We do not guarantee results, income, product quality or suitability."], ["Health/water products", "Water, health and device recommendations do not make medical claims or health outcome guarantees."], ["Check before buying", "Users should independently verify whether a product fits their needs."]] },
    "ai-transparentnost": { title: "AI Transparency", description: "How DaniniNet uses AI.", eyebrow: "AI Transparency", intro: "AI tools may help structure ideas, prepare drafts, organize content and analyze information, but AI is not an authority.", sections: [["AI is not an authority", "AI does not make final decisions and does not replace professional review."], ["Method", "Ask AI — AI asks you means: the human starts the intent, AI may ask up to three clarifying questions, then moves to analysis, artifact and next step."], ["Artifact output", "Pages, PDFs, templates, courses and forms may be created as artifacts, but not published without human control."], ["Responsibility", "Important content should pass human review and editorial judgment."]] },
    "health-disclaimer": { title: "Health Disclaimer", description: "Boundaries for health, water and lifestyle content.", eyebrow: "Health", intro: "Health, water, nutrition and lifestyle content is educational and informational only.", sections: [["Not medical advice", "It is not medical advice, diagnosis, therapy or a replacement for a doctor."], ["No health guarantees", "We do not guarantee health outcomes or product effects."], ["Affiliate products", "Filter, device, eBook and health/water recommendations must be clearly disclosed and avoid medical claims."], ["Professional help", "For health questions, consult a qualified health professional."]] },
    "refund-policy": { title: "Refund Policy", description: "Refund policy for DaniniNet digital products.", eyebrow: "Refund / Support", intro: "Digital products are delivered through external checkout and delivery systems. This page explains basic refund and support logic.", sections: [["Digital delivery", "PDF guides, Bonus Packs, templates and e-books may be delivered immediately after purchase."], ["Gumroad rules", "If purchase goes through Gumroad, Gumroad terms, delivery logic and refund processes may also apply."], ["Support before refund", "If files do not arrive, first check checkout email, spam/promotions and Gumroad library, then send a support request."], ["No result guarantee", "Lack of business, health or investment results is not proof of product defect because results are not guaranteed."]] },
  },
};

export function generateStaticParams() {
  return ["sr", "de", "en"].flatMap((locale) => allowedSlugs.map((slug) => ({ locale, slug })));
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> {
  const { locale, slug } = await params;
  const lang: Locale = normalizeLocale(locale);
  if (!allowedSlugs.includes(slug as LegalSlug)) return {};
  const page = copy[lang][slug as LegalSlug];
  return { title: `${page.title} | DaniniNet`, description: page.description, alternates: { canonical: `/${lang}/legal/${slug}` } };
}

export default async function LegalSubPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params;
  const lang: Locale = normalizeLocale(locale);
  if (!allowedSlugs.includes(slug as LegalSlug)) notFound();
  const page = copy[lang][slug as LegalSlug];

  return (
    <SiteShell locale={lang} currentPath={`/${lang}/legal/${slug}`}>
      <SectionIntro eyebrow={page.eyebrow} title={page.title} text={page.intro} />
      <section className="mx-auto grid max-w-7xl gap-5 px-6 pb-10 md:grid-cols-2 xl:grid-cols-3">
        {page.sections.map(([title, text]) => (
          <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-7 shadow-sm">
            <h2 className="text-2xl font-semibold">{title}</h2>
            <p className="mt-4 leading-8 text-[#706a5d]">{text}</p>
          </article>
        ))}
      </section>
      {page.auditNote ? (
        <section className="mx-auto max-w-7xl px-6 pb-16">
          <div className="rounded-[2rem] border border-[#d7b46a]/30 bg-[#fffaf1] p-6 leading-8 text-[#706a5d]">
            <strong className="text-[#07142b]">Audit note:</strong> {page.auditNote}
          </div>
        </section>
      ) : null}
    </SiteShell>
  );
}
