import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";
type LegalSlug = "impressum" | "privacy" | "cookies" | "terms" | "disclaimer" | "affiliate-disclosure" | "ai-transparentnost" | "health-disclaimer";

const allowedSlugs: LegalSlug[] = ["impressum", "privacy", "cookies", "terms", "disclaimer", "affiliate-disclosure", "ai-transparentnost", "health-disclaimer"];

const copy: Record<Locale, Record<LegalSlug, { title: string; description: string; eyebrow: string; intro: string; sections: [string, string][] }>> = {
  sr: {
    impressum: { title: "Impressum", description: "Kontakt i osnovne informacije o DaniniNet projektu.", eyebrow: "Legal & Trust", intro: "Ova stranica prikazuje osnovni kontakt i identitet projekta DaniniNet. Konačni poslovni podaci moraju biti usklađeni sa stvarnim podacima vlasnika pre ozbiljnog DACH prometa.", sections: [["Kontakt", "DaniniNet · Email: dragangaganet@gmail.com"], ["Napomena", "Informacije na ovoj stranici ne predstavljaju pravni savet i treba ih proveriti prema važećem lokalnom pravu."]] },
    privacy: { title: "Privacy / GDPR", description: "Osnovni principi privatnosti i obrade podataka na DaniniNet sajtu.", eyebrow: "Data protection", intro: "DaniniNet obrađuje minimum podataka potreban za komunikaciju, kupovinu, isporuku digitalnih proizvoda i podršku.", sections: [["Svrha obrade", "Podaci se mogu koristiti za kontakt, podršku, isporuku proizvoda, newsletter i osnovnu analitiku ako je korisnik dao saglasnost."], ["Eksterni servisi", "Kupovina i isporuka mogu ići preko Gumroad-a, a email komunikacija preko odgovarajućih email servisa. Korisnik treba proveriti i njihove politike privatnosti."], ["Prava korisnika", "Korisnik može zatražiti informaciju, ispravku ili brisanje podataka kontaktom na support email."]] },
    cookies: { title: "Cookies", description: "Informacije o kolačićima, analitici i tehničkoj funkcionalnosti.", eyebrow: "Cookies", intro: "DaniniNet može koristiti tehničke kolačiće, osnovnu analitiku i buduće marketing alate samo u skladu sa pravilima privatnosti i saglasnosti korisnika.", sections: [["Tehnički kolačići", "Koriste se za osnovnu funkcionalnost sajta."], ["Analitika", "Ako je uključena, analitika treba da se koristi uz odgovarajuću saglasnost i minimalno prikupljanje podataka."], ["Kontrola", "Korisnik može upravljati kolačićima kroz browser i eventualni cookie banner."]] },
    terms: { title: "Terms of Use", description: "Uslovi korišćenja DaniniNet sajta i digitalnih proizvoda.", eyebrow: "Terms", intro: "Korišćenjem DaniniNet sajta korisnik prihvata da je sadržaj edukativnog i informativnog karaktera.", sections: [["Digitalni proizvodi", "PDF vodiči, bonus materijali i usluge služe za edukaciju i strukturisanje procesa."], ["Eksterni checkout", "Kupovina može ići preko eksternih servisa kao što je Gumroad, prema njihovim pravilima."], ["Odgovornost korisnika", "Korisnik samostalno proverava pravne, finansijske, tehničke, zdravstvene i druge odluke sa kvalifikovanim stručnjacima."]] },
    disclaimer: { title: "Disclaimer", description: "Glavni disclaimer za DaniniNet sadržaj, proizvode i usluge.", eyebrow: "Disclaimer", intro: "DaniniNet objavljuje edukativni i informativni sadržaj iz oblasti digitalnog marketinga, affiliate marketinga, AI alata, zdravog stila života i digitalnih proizvoda.", sections: [["Bez profesionalnog saveta", "Sadržaj ne predstavlja pravni, finansijski, poreski, medicinski, investicioni, urbanistički ili profesionalni savet."], ["Bez garancija", "Ne garantujemo zaradu, prodaju, poslovni uspeh, zdravstveni rezultat, investitora ili bilo koji konkretan ishod."], ["Ljudska odluka", "Korisnik samostalno donosi odluke i po potrebi treba da se konsultuje sa kvalifikovanim stručnjakom."]] },
    "affiliate-disclosure": { title: "Affiliate Disclosure", description: "Transparentna affiliate napomena za DaniniNet preporuke.", eyebrow: "Affiliate", intro: "Neki linkovi na DaniniNet sajtu mogu biti affiliate linkovi. Ako kupite preko takvih linkova, DaniniNet može ostvariti proviziju bez dodatnog troška za vas.", sections: [["Transparentnost", "Affiliate odnos ne menja obavezu da sadržaj bude informativan, transparentan i odgovoran."], ["Bez garancija", "Ne garantujemo rezultate, zaradu, kvalitet proizvoda ili pogodnost za svakog korisnika."], ["Provera", "Pre kupovine korisnik treba samostalno da proveri da li proizvod odgovara njegovim potrebama."]] },
    "ai-transparentnost": { title: "AI transparentnost", description: "Kako DaniniNet koristi AI kroz metodu Pitaj AI — AI pita tebe.", eyebrow: "AI Transparency", intro: "Na DaniniNet-u se AI alati mogu koristiti kao pomoć u strukturiranju ideja, pripremi nacrta, organizaciji sadržaja i analizi.", sections: [["AI nije autoritet", "AI ne donosi konačne odluke i ne zamenjuje stručnu proveru."], ["Metoda", "Pitaj AI — AI pita tebe znači da AI pomaže kroz pitanja, razjašnjenje i strukturu, a ne kroz slepo kopiranje promptova."], ["Odgovornost", "Svaki važan sadržaj treba da prođe ljudsku proveru i uredničku procenu."]] },
    "health-disclaimer": { title: "Health Disclaimer", description: "Granice za sadržaj o zdravlju, vodi i navikama.", eyebrow: "Health", intro: "Sadržaj o zdravlju, vodi, navikama, ishrani i zdravom stilu života ima isključivo informativnu i edukativnu svrhu.", sections: [["Nije medicinski savet", "Sadržaj ne predstavlja medicinski savet, dijagnozu, terapiju ili zamenu za konsultaciju sa lekarom."], ["Bez zdravstvenih garancija", "Ne garantujemo zdravstveni rezultat, poboljšanje stanja ili efekat proizvoda."], ["Stručna pomoć", "Za zdravstvena pitanja potrebno je konsultovati kvalifikovanog zdravstvenog stručnjaka."]] },
  },
  de: {
    impressum: { title: "Impressum", description: "Kontakt und Basisinformationen zu DaniniNet.", eyebrow: "Legal & Trust", intro: "Diese Seite zeigt grundlegende Kontakt- und Projektinformationen. Finale Geschäftsdaten müssen vor ernsthaftem DACH-Traffic mit realen Angaben abgeglichen werden.", sections: [["Kontakt", "DaniniNet · Email: dragangaganet@gmail.com"], ["Hinweis", "Diese Angaben sind keine Rechtsberatung und sollten lokal geprüft werden."]] },
    privacy: { title: "Privacy / DSGVO", description: "Datenschutzgrundlagen für DaniniNet.", eyebrow: "Datenschutz", intro: "DaniniNet verarbeitet nur Daten, die für Kommunikation, Kauf, Produktlieferung und Support erforderlich sind.", sections: [["Zweck", "Daten können für Kontakt, Support, Produktlieferung, Newsletter und Analyse nach Einwilligung genutzt werden."], ["Externe Dienste", "Kauf und Lieferung können über Gumroad und E-Mail-Dienste erfolgen."], ["Nutzerrechte", "Nutzer können Auskunft, Berichtigung oder Löschung per E-Mail anfragen."]] },
    cookies: { title: "Cookies", description: "Informationen zu Cookies und Analyse.", eyebrow: "Cookies", intro: "DaniniNet kann technische Cookies, Analyse und künftige Marketing-Tools nur im Rahmen von Datenschutz und Einwilligung nutzen.", sections: [["Technische Cookies", "Für Basisfunktionen der Website."], ["Analyse", "Nur mit passender Einwilligung und minimaler Datenerhebung."], ["Kontrolle", "Nutzer können Cookies im Browser und über Cookie-Banner steuern."]] },
    terms: { title: "Terms of Use", description: "Nutzungsbedingungen für DaniniNet.", eyebrow: "Terms", intro: "Die Nutzung von DaniniNet bedeutet, dass Inhalte als edukativ und informativ verstanden werden.", sections: [["Digitale Produkte", "PDFs, Bonusmaterial und Services dienen der Bildung und Strukturierung."], ["Externer Checkout", "Käufe können über Dienste wie Gumroad laufen."], ["Verantwortung", "Nutzer prüfen wichtige Entscheidungen mit qualifizierten Fachleuten."]] },
    disclaimer: { title: "Disclaimer", description: "Haupt-Disclaimer für DaniniNet.", eyebrow: "Disclaimer", intro: "DaniniNet veröffentlicht edukative und informative Inhalte zu digitalem Marketing, Affiliate, KI, Lifestyle und digitalen Produkten.", sections: [["Keine Beratung", "Keine Rechts-, Finanz-, Steuer-, Medizin-, Investment- oder Fachberatung."], ["Keine Garantien", "Keine Garantie für Einkommen, Verkauf, Erfolg, Gesundheit oder konkrete Ergebnisse."], ["Eigene Entscheidung", "Nutzer treffen Entscheidungen eigenverantwortlich und holen bei Bedarf Fachrat ein."]] },
    "affiliate-disclosure": { title: "Affiliate Disclosure", description: "Affiliate-Hinweis für DaniniNet.", eyebrow: "Affiliate", intro: "Einige Links auf DaniniNet können Affiliate-Links sein. Bei Kauf kann DaniniNet eine Provision erhalten, ohne Mehrkosten für Nutzer.", sections: [["Transparenz", "Affiliate-Beziehungen ändern nicht die Pflicht zu verantwortlichen Inhalten."], ["Keine Garantien", "Keine Garantie für Ergebnisse, Einkommen, Produktqualität oder Eignung."], ["Prüfung", "Nutzer sollten vor Kauf prüfen, ob ein Produkt passt."]] },
    "ai-transparentnost": { title: "KI-Transparenz", description: "Wie DaniniNet KI nutzt.", eyebrow: "AI Transparency", intro: "KI kann bei Struktur, Entwürfen, Organisation und Analyse helfen.", sections: [["KI ist keine Autorität", "KI ersetzt keine Entscheidung und keine Fachprüfung."], ["Methode", "Frag die KI — die KI fragt dich steht für Fragen und Struktur statt blindem Prompt-Kopieren."], ["Verantwortung", "Wichtige Inhalte brauchen menschliche Prüfung."]] },
    "health-disclaimer": { title: "Health Disclaimer", description: "Grenzen für Health- und Wasser-Inhalte.", eyebrow: "Health", intro: "Gesundheits-, Wasser- und Lifestyle-Inhalte dienen nur Bildung und Information.", sections: [["Keine medizinische Beratung", "Keine Diagnose, Therapie oder Ersatz für ärztliche Beratung."], ["Keine Garantien", "Keine Garantie für gesundheitliche Ergebnisse."], ["Fachliche Hilfe", "Bei Gesundheitsfragen qualifizierte Fachleute konsultieren."]] },
  },
  en: {
    impressum: { title: "Imprint", description: "Contact and basic DaniniNet project information.", eyebrow: "Legal & Trust", intro: "This page provides basic contact and project identity information. Final business details should be aligned with real owner data before serious public use.", sections: [["Contact", "DaniniNet · Email: dragangaganet@gmail.com"], ["Note", "This information is not legal advice and should be checked against local law."]] },
    privacy: { title: "Privacy / GDPR", description: "Privacy principles for DaniniNet.", eyebrow: "Data protection", intro: "DaniniNet processes the minimum data needed for communication, purchase, product delivery and support.", sections: [["Purpose", "Data may be used for contact, support, product delivery, newsletter and basic analytics with consent."], ["External services", "Purchases and delivery may use Gumroad and email services."], ["User rights", "Users may request information, correction or deletion by email."]] },
    cookies: { title: "Cookies", description: "Cookie and analytics information.", eyebrow: "Cookies", intro: "DaniniNet may use technical cookies, analytics and future marketing tools only within privacy and consent rules.", sections: [["Technical cookies", "Used for basic site functionality."], ["Analytics", "Should be used with consent and minimal data collection."], ["Control", "Users can manage cookies in browser and cookie banner settings."]] },
    terms: { title: "Terms of Use", description: "Terms for using DaniniNet.", eyebrow: "Terms", intro: "Using DaniniNet means understanding the content as educational and informational.", sections: [["Digital products", "PDFs, bonus materials and services are for education and process structure."], ["External checkout", "Purchases may use external services such as Gumroad."], ["User responsibility", "Users should verify important decisions with qualified professionals."]] },
    disclaimer: { title: "Disclaimer", description: "Main disclaimer for DaniniNet.", eyebrow: "Disclaimer", intro: "DaniniNet publishes educational and informational content about digital marketing, affiliate marketing, AI tools, lifestyle and digital products.", sections: [["No professional advice", "Content is not legal, financial, tax, medical, investment or professional advice."], ["No guarantees", "We do not guarantee income, sales, business success, health results or any specific outcome."], ["Human decision", "Users make decisions independently and should consult qualified professionals when needed."]] },
    "affiliate-disclosure": { title: "Affiliate Disclosure", description: "Affiliate disclosure for DaniniNet recommendations.", eyebrow: "Affiliate", intro: "Some links on DaniniNet may be affiliate links. If you buy through such links, DaniniNet may earn a commission at no additional cost to you.", sections: [["Transparency", "Affiliate relationships do not change the duty to keep content informative and responsible."], ["No guarantees", "We do not guarantee results, income, product quality or suitability."], ["Check before buying", "Users should independently verify whether a product fits their needs."]] },
    "ai-transparentnost": { title: "AI Transparency", description: "How DaniniNet uses AI.", eyebrow: "AI Transparency", intro: "AI tools may help structure ideas, prepare drafts, organize content and analyze information.", sections: [["AI is not an authority", "AI does not make final decisions and does not replace professional review."], ["Method", "Ask AI — AI asks you means questions and structure, not blind prompt copying."], ["Responsibility", "Important content should pass human review and editorial judgment."]] },
    "health-disclaimer": { title: "Health Disclaimer", description: "Boundaries for health, water and lifestyle content.", eyebrow: "Health", intro: "Health, water, nutrition and lifestyle content is educational and informational only.", sections: [["Not medical advice", "It is not medical advice, diagnosis, therapy or a replacement for a doctor."], ["No health guarantees", "We do not guarantee health outcomes or product effects."], ["Professional help", "For health questions, consult a qualified health professional."]] },
  },
};

export function generateStaticParams() {
  return ["sr", "de", "en"].flatMap((locale) => allowedSlugs.map((slug) => ({ locale, slug })));
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> {
  const { locale, slug } = await params;
  const lang: Locale = normalizeLocale(locale);
  if (!allowedSlugs.includes(slug as LegalSlug)) return {};
  const page = copy[lang][slug as LegalSlug];
  return { title: `${page.title} | DaniniNet`, description: page.description, alternates: { canonical: `/${lang}/legal/${slug}` } };
}

export default async function LegalSubPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params;
  const lang: Locale = normalizeLocale(locale);
  if (!allowedSlugs.includes(slug as LegalSlug)) notFound();
  const page = copy[lang][slug as LegalSlug];

  return (
    <SiteShell locale={lang} currentPath={`/${lang}/legal/${slug}`}>
      <SectionIntro eyebrow={page.eyebrow} title={page.title} text={page.intro} />
      <section className="mx-auto grid max-w-7xl gap-5 px-6 pb-16 md:grid-cols-3">
        {page.sections.map(([title, text]) => (
          <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-7 shadow-sm">
            <h2 className="text-2xl font-semibold">{title}</h2>
            <p className="mt-4 leading-8 text-[#706a5d]">{text}</p>
          </article>
        ))}
      </section>
    </SiteShell>
  );
}
