import Link from "next/link";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";
const copy = {
  sr: { eyebrow: "Health disclaimer", title: "Health / Water sadržaj je edukativan, ne medicinski savet.", text: "Budući DaniniNet health/water pravac može obrađivati vodu, rutine, zdrav stil života i affiliate proizvode, ali bez medicinskih obećanja i bez zamene za stručnjaka.", blocks: [["Edukativni karakter", "Sadržaj o vodi, navikama i rutinama služi za informisanje i ličnu organizaciju."], ["Nema medicinskih tvrdnji", "Ne tvrdi se da proizvod, navika ili rutina leči, sprečava bolest ili garantuje zdravstveni rezultat."], ["Stručna provera", "Za simptome, terapiju, dijagnozu, ishranu, suplemente ili medicinske odluke korisnik treba da se obrati kvalifikovanom stručnjaku."], ["Affiliate preporuke", "Ako postoje affiliate linkovi u health/water sadržaju, moraju biti jasno označeni i bez tvrdnji o garantovanom efektu." ]]},
  de: { eyebrow: "Health Disclaimer", title: "Health / Water Inhalte sind edukativ, keine medizinische Beratung.", text: "Der künftige DaniniNet Health/Water Bereich kann Wasser, Routinen, gesunden Lebensstil und Affiliate-Produkte behandeln, aber ohne medizinische Versprechen und ohne Ersatz für Fachleute.", blocks: [["Bildungscharakter", "Inhalte zu Wasser, Gewohnheiten und Routinen dienen Information und persönlicher Organisation."], ["Keine medizinischen Claims", "Es wird nicht behauptet, dass ein Produkt, eine Gewohnheit oder Routine heilt, Krankheiten verhindert oder gesundheitliche Ergebnisse garantiert."], ["Fachprüfung", "Bei Symptomen, Therapie, Diagnose, Ernährung, Supplements oder medizinischen Entscheidungen sollten qualifizierte Fachleute konsultiert werden."], ["Affiliate Empfehlungen", "Affiliate-Links im Health/Water Bereich müssen klar markiert sein und dürfen keine garantierten Wirkungen versprechen." ]]},
  en: { eyebrow: "Health disclaimer", title: "Health / Water content is educational, not medical advice.", text: "The future DaniniNet health/water direction may cover water, routines, healthy lifestyle and affiliate products, but without medical promises and without replacing professionals.", blocks: [["Educational nature", "Content about water, habits and routines is for information and personal organization."], ["No medical claims", "No product, habit or routine is presented as healing, preventing disease or guaranteeing health outcomes."], ["Professional review", "For symptoms, therapy, diagnosis, nutrition, supplements or medical decisions, users should consult qualified professionals."], ["Affiliate recommendations", "Affiliate links in health/water content must be clearly disclosed and must not promise guaranteed effects." ]]},
} as const;
export default async function HealthDisclaimerPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; const lang: Locale = normalizeLocale(locale); const t = copy[lang]; return <SiteShell locale={lang} currentPath={`/${lang}/legal/health-disclaimer`}><SectionIntro eyebrow={t.eyebrow} title={t.title} text={t.text}/><section className="mx-auto grid max-w-7xl gap-6 px-6 pb-16 md:grid-cols-2">{t.blocks.map(([title,text]) => <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-4 leading-8 text-[#706a5d]">{text}</p></article>)}</section><section className="bg-[#07142b] text-white"><div className="mx-auto max-w-7xl px-6 py-14"><Link href={`/${lang}/legal`} className="inline-flex rounded-full bg-[#d9ecff] px-6 py-3 text-sm font-semibold text-[#07142b]">Legal & Trust</Link></div></section></SiteShell>; }
