import Link from "next/link";
import { SectionIntro, SiteShell, normalizeLocale } from "@/components/layout/SiteShell";

type Locale = "sr" | "de" | "en";

const copy = {
  sr: { eyebrow: "Privacy / GDPR", title: "Privatnost, podaci i digitalna isporuka.", text: "DaniniNet obrađuje podatke samo kada postoji konkretna svrha: kontakt, kupovina, isporuka digitalnog proizvoda, newsletter, support ili tehnička funkcionalnost sajta.", notice: "Radni GDPR-aware okvir. Pre finalne javne upotrebe uskladiti sa stvarnim poslovnim podacima, alatima i advokatom.", blocks: [["Koji podaci", "Ime, e-mail, poruka, status kupovine, delivery status, newsletter prijava, support zahtev i osnovni tehnički podaci."], ["Zašto", "Odgovor na zahtev, obrada kupovine, isporuka proizvoda, korisnička podrška, dokaz komunikacije, bezbednost i dobrovoljni newsletter."], ["Checkout", "Gumroad ili drugi checkout servis može obrađivati plaćanje, potvrdu, pristup i isporuku. Njihova pravila privatnosti važe za njihov deo toka."], ["E-mail", "Brevo ili drugi e-mail alat može se koristiti za newsletter, delivery poruke i support. Newsletter mora imati jasnu prijavu i mogućnost odjave."], ["AI", "AI može pomagati u strukturi i obradi sadržaja, ali privatni podaci se ne smeju nepotrebno unositi u AI alate. Osetljive informacije se minimizuju."], ["Prava korisnika", "Korisnik može tražiti pristup, ispravku, brisanje, ograničenje, prenosivost ili prigovor kada je to primenljivo."], ["Čuvanje", "Podaci se čuvaju onoliko koliko je potrebno za svrhu, dokaz kupovine, support, računovodstvo ili zakonsku obavezu."], ["Princip", "Bez skrivenog profilisanja, bez prodaje podataka i bez nepotrebnog prikupljanja." ]], final: "Manje podataka, jasnija svrha, bolja kontrola." },
  de: { eyebrow: "Privacy / DSGVO", title: "Datenschutz, Daten und digitale Lieferung.", text: "DaniniNet verarbeitet Daten nur mit konkretem Zweck: Kontakt, Kauf, Lieferung digitaler Produkte, Newsletter, Support oder technische Website-Funktion.", notice: "DSGVO-orientierter Arbeitsrahmen. Vor finaler öffentlicher Nutzung mit realen Geschäftsdaten, Tools und Rechtsprüfung abgleichen.", blocks: [["Welche Daten", "Name, E-Mail, Nachricht, Kaufstatus, Lieferstatus, Newsletter-Anmeldung, Support-Anfrage und grundlegende technische Daten."], ["Warum", "Antwort auf Anfrage, Kaufabwicklung, Produktlieferung, Kundensupport, Kommunikationsnachweis, Sicherheit und freiwilliger Newsletter."], ["Checkout", "Gumroad oder ein anderer Checkout-Dienst kann Zahlung, Bestätigung, Zugriff und Lieferung verarbeiten. Deren Datenschutzregeln gelten für ihren Teil des Ablaufs."], ["E-Mail", "Brevo oder ein anderer E-Mail-Dienst kann für Newsletter, Delivery-Mails und Support genutzt werden. Newsletter braucht klare Anmeldung und Abmeldung."], ["AI", "AI kann bei Struktur und Inhaltsarbeit unterstützen, aber private Daten sollen nicht unnötig in AI-Tools eingegeben werden. Sensible Informationen werden minimiert."], ["Nutzerrechte", "Nutzer können Zugang, Berichtigung, Löschung, Einschränkung, Übertragbarkeit oder Widerspruch verlangen, sofern anwendbar."], ["Speicherung", "Daten werden nur so lange gespeichert, wie Zweck, Kaufnachweis, Support, Buchhaltung oder gesetzliche Pflichten es erfordern."], ["Prinzip", "Kein verstecktes Profiling, kein Verkauf von Daten und keine unnötige Datenerhebung." ]], final: "Weniger Daten, klarerer Zweck, bessere Kontrolle." },
  en: { eyebrow: "Privacy / GDPR", title: "Privacy, data and digital delivery.", text: "DaniniNet processes data only for a concrete purpose: contact, purchase, digital product delivery, newsletter, support or technical website functionality.", notice: "GDPR-aware working framework. Before final public use, align with real business details, tools and legal review.", blocks: [["Which data", "Name, email, message, purchase status, delivery status, newsletter signup, support request and basic technical data."], ["Why", "Replying to requests, processing purchases, delivering products, customer support, communication records, security and voluntary newsletter."], ["Checkout", "Gumroad or another checkout provider may process payment, confirmation, access and delivery. Their privacy rules apply to their part of the flow."], ["Email", "Brevo or another email tool may be used for newsletters, delivery emails and support. Newsletter requires clear signup and unsubscribe."], ["AI", "AI may support structure and content work, but private data should not be entered into AI tools unnecessarily. Sensitive information is minimized."], ["User rights", "Users may request access, correction, deletion, restriction, portability or objection where applicable."], ["Retention", "Data is kept only as long as needed for purpose, purchase proof, support, accounting or legal duties."], ["Principle", "No hidden profiling, no sale of data and no unnecessary collection." ]], final: "Less data, clearer purpose, better control." },
} as const;

export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const lang: Locale = normalizeLocale(locale);
  const t = copy[lang];
  return <SiteShell locale={lang} currentPath={`/${lang}/legal/privacy`}><SectionIntro eyebrow={t.eyebrow} title={t.title} text={t.text}/><section className="mx-auto max-w-7xl px-6 pb-10"><div className="rounded-[2rem] border border-[#d7b46a]/40 bg-[#fff8e7] p-7 text-[#3b3426] shadow-sm"><p className="text-sm uppercase tracking-[0.22em] text-[#9a6b1f]">Legal notice</p><p className="mt-3 max-w-5xl leading-8">{t.notice}</p></div></section><section className="mx-auto grid max-w-7xl gap-6 px-6 pb-16 md:grid-cols-2">{t.blocks.map(([title,text]) => <article key={title} className="rounded-[2rem] border border-black/10 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-[#15130f]">{title}</h2><p className="mt-4 leading-8 text-[#706a5d]">{text}</p></article>)}</section><section className="bg-[#07142b] text-white"><div className="mx-auto max-w-7xl px-6 py-14"><p className="mt-4 max-w-4xl text-xl leading-9 text-slate-300">{t.final}</p><Link href={`/${lang}/legal`} className="mt-8 inline-flex rounded-full bg-[#d9ecff] px-6 py-3 text-sm font-semibold text-[#07142b]">Legal & Trust</Link></div></section></SiteShell>;
}
